/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AddIds : A list of role encoded IDs defining roles that should be able to add items to the library.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddIds {
}

impl AddIds {
    /// A list of role encoded IDs defining roles that should be able to add items to the library.
    pub fn new() -> AddIds {
        AddIds {
        }
    }
}


