/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BasicRoleModel {
    /// Encoded ID of the role
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the role
    #[serde(rename = "name")]
    pub name: String,
    /// Type or category of the role
    #[serde(rename = "type")]
    pub r#type: String,
}

impl BasicRoleModel {
    pub fn new(id: String, name: String, r#type: String) -> BasicRoleModel {
        BasicRoleModel {
            id,
            name,
            r#type,
        }
    }
}


