/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BulkOperationItemError : Base model definition with common configuration used by all derived models.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkOperationItemError {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "item")]
    pub item: Box<crate::models::HistoryContentItem>,
}

impl BulkOperationItemError {
    /// Base model definition with common configuration used by all derived models.
    pub fn new(error: String, item: crate::models::HistoryContentItem) -> BulkOperationItemError {
        BulkOperationItemError {
            error,
            item: Box::new(item),
        }
    }
}


