/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChangeDbkeyOperationParams : Base model definition with common configuration used by all derived models.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChangeDbkeyOperationParams {
    #[serde(rename = "dbkey")]
    pub dbkey: String,
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl ChangeDbkeyOperationParams {
    /// Base model definition with common configuration used by all derived models.
    pub fn new(dbkey: String, r#type: RHashType) -> ChangeDbkeyOperationParams {
        ChangeDbkeyOperationParams {
            dbkey,
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "change_dbkey")]
    ChangeDbkey,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::ChangeDbkey
    }
}

