/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ColletionSourceType : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ColletionSourceType {
    #[serde(rename = "hda")]
    Hda,
    #[serde(rename = "ldda")]
    Ldda,
    #[serde(rename = "hdca")]
    Hdca,
    #[serde(rename = "new_collection")]
    NewCollection,

}

impl ToString for ColletionSourceType {
    fn to_string(&self) -> String {
        match self {
            Self::Hda => String::from("hda"),
            Self::Ldda => String::from("ldda"),
            Self::Hdca => String::from("hdca"),
            Self::NewCollection => String::from("new_collection"),
        }
    }
}

impl Default for ColletionSourceType {
    fn default() -> ColletionSourceType {
        Self::Hda
    }
}




