/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CompositeItems {
    #[serde(rename = "elements")]
    pub elements: Vec<crate::models::ElementsInner>,
}

impl CompositeItems {
    pub fn new(elements: Vec<crate::models::ElementsInner>) -> CompositeItems {
        CompositeItems {
            elements,
        }
    }
}


