/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateLibraryFolderPayload {
    /// A detailed description of the library folder.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The name of the library folder.
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateLibraryFolderPayload {
    pub fn new(name: String) -> CreateLibraryFolderPayload {
        CreateLibraryFolderPayload {
            description: None,
            name,
        }
    }
}


