/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateNewCollectionPayload : Base model definition with common configuration used by all derived models.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateNewCollectionPayload {
    /// The type of the collection, can be `list`, `paired`, or define subcollections using `:` as separator like `list:paired` or `list:list`.
    #[serde(rename = "collection_type", skip_serializing_if = "Option::is_none")]
    pub collection_type: Option<String>,
    /// Whether to create a copy of the source HDAs for the new collection.
    #[serde(rename = "copy_elements", skip_serializing_if = "Option::is_none")]
    pub copy_elements: Option<bool>,
    /// List of elements that should be in the new collection.
    #[serde(rename = "element_identifiers", skip_serializing_if = "Option::is_none")]
    pub element_identifiers: Option<Vec<crate::models::CollectionElementIdentifier>>,
    /// The ID of the history that will contain the collection. Required if `instance_type=library`.
    #[serde(rename = "folder_id", skip_serializing_if = "Option::is_none")]
    pub folder_id: Option<String>,
    /// Whether to mark the original HDAs as hidden.
    #[serde(rename = "hide_source_items", skip_serializing_if = "Option::is_none")]
    pub hide_source_items: Option<bool>,
    /// The ID of the history that will contain the collection. Required if `instance_type=history`.
    #[serde(rename = "history_id", skip_serializing_if = "Option::is_none")]
    pub history_id: Option<String>,
    /// The type of the instance, either `history` (default) or `library`.
    #[serde(rename = "instance_type", skip_serializing_if = "Option::is_none")]
    pub instance_type: Option<Box<crate::models::DatasetCollectionInstanceType>>,
    /// The name of the new collection.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl CreateNewCollectionPayload {
    /// Base model definition with common configuration used by all derived models.
    pub fn new() -> CreateNewCollectionPayload {
        CreateNewCollectionPayload {
            collection_type: None,
            copy_elements: None,
            element_identifiers: None,
            folder_id: None,
            hide_source_items: None,
            history_id: None,
            instance_type: None,
            name: None,
        }
    }
}


