/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateHistoryContentFromStore : Base model definition with common configuration used by all derived models.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateHistoryContentFromStore {
    #[serde(rename = "model_store_format", skip_serializing_if = "Option::is_none")]
    pub model_store_format: Option<crate::models::ModelStoreFormat>,
    #[serde(rename = "store_content_uri", skip_serializing_if = "Option::is_none")]
    pub store_content_uri: Option<String>,
    #[serde(rename = "store_dict", skip_serializing_if = "Option::is_none")]
    pub store_dict: Option<serde_json::Value>,
}

impl CreateHistoryContentFromStore {
    /// Base model definition with common configuration used by all derived models.
    pub fn new() -> CreateHistoryContentFromStore {
        CreateHistoryContentFromStore {
            model_store_format: None,
            store_content_uri: None,
            store_dict: None,
        }
    }
}


