/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DatatypeConverter {
    /// Source type for conversion
    #[serde(rename = "source")]
    pub source: String,
    /// Target type for conversion
    #[serde(rename = "target")]
    pub target: String,
    /// The converter tool identifier
    #[serde(rename = "tool_id")]
    pub tool_id: String,
}

impl DatatypeConverter {
    pub fn new(source: String, target: String, tool_id: String) -> DatatypeConverter {
        DatatypeConverter {
            source,
            target,
            tool_id,
        }
    }
}


