/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DatatypesCombinedMap {
    /// List of datatypes extensions
    #[serde(rename = "datatypes")]
    pub datatypes: Vec<String>,
    #[serde(rename = "datatypes_mapping")]
    pub datatypes_mapping: Box<crate::models::DatatypesMapping>,
}

impl DatatypesCombinedMap {
    pub fn new(datatypes: Vec<String>, datatypes_mapping: crate::models::DatatypesMapping) -> DatatypesCombinedMap {
        DatatypesCombinedMap {
            datatypes,
            datatypes_mapping: Box::new(datatypes_mapping),
        }
    }
}


