/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DateRangeMinimum : Limit listing of jobs to those that are updated after specified date (e.g. '2014-01-01')



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DateRangeMinimum {
}

impl DateRangeMinimum {
    /// Limit listing of jobs to those that are updated after specified date (e.g. '2014-01-01')
    pub fn new() -> DateRangeMinimum {
        DateRangeMinimum {
        }
    }
}


