/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DcObject : Dataset Collection Object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DcObject {
    /// The type of the collection, can be `list`, `paired`, or define subcollections using `:` as separator like `list:paired` or `list:list`.
    #[serde(rename = "collection_type", skip_serializing_if = "Option::is_none")]
    pub collection_type: Option<String>,
    /// The relative URL to access the contents of this History.
    #[serde(rename = "contents_url", skip_serializing_if = "Option::is_none")]
    pub contents_url: Option<String>,
    /// The number of elements contained in the dataset collection. It may be None or undefined if the collection could not be populated.
    #[serde(rename = "element_count", skip_serializing_if = "Option::is_none")]
    pub element_count: Option<i32>,
    /// The summary information of each of the elements inside the dataset collection.
    #[serde(rename = "elements", skip_serializing_if = "Option::is_none")]
    pub elements: Option<Vec<crate::models::DceSummary>>,
    /// The encoded ID of this entity.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the database model class.
    #[serde(rename = "model_class", skip_serializing_if = "Option::is_none")]
    pub model_class: Option<String>,
    /// Whether the dataset collection elements (and any subcollections elements) were successfully populated.
    #[serde(rename = "populated", skip_serializing_if = "Option::is_none")]
    pub populated: Option<bool>,
}

impl DcObject {
    /// Dataset Collection Object
    pub fn new(id: String) -> DcObject {
        DcObject {
            collection_type: None,
            contents_url: None,
            element_count: None,
            elements: None,
            id,
            model_class: None,
            populated: None,
        }
    }
}


