/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DefaultQuota {
    /// The name of the database model class.
    #[serde(rename = "model_class", skip_serializing_if = "Option::is_none")]
    pub model_class: Option<String>,
    /// The type of the default quota. Either one of:  - `registered`: the associated quota will affect registered users.  - `unregistered`: the associated quota will affect unregistered users. 
    #[serde(rename = "type")]
    pub r#type: Box<crate::models::DefaultQuotaTypes>,
}

impl DefaultQuota {
    pub fn new(r#type: crate::models::DefaultQuotaTypes) -> DefaultQuota {
        DefaultQuota {
            model_class: None,
            r#type: Box::new(r#type),
        }
    }
}


