/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "r#type")]
pub enum Destination {
    #[serde(rename="hdas")]
    HdaDestination {
    },
    #[serde(rename="library")]
    LibraryDestination {
        /// Description for library to create
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
        /// Must specify a library name
        #[serde(rename = "name")]
        name: String,
        /// Description for library to create
        #[serde(rename = "synopsis", skip_serializing_if = "Option::is_none")]
        synopsis: Option<String>,
    },
    #[serde(rename="library_folder")]
    LibraryFolderDestination {
        #[serde(rename = "library_folder_id")]
        library_folder_id: String,
    },
}



/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "library")]
    Library,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Library
    }
}

