/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ElementsFromType : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ElementsFromType {
    #[serde(rename = "archive")]
    Archive,
    #[serde(rename = "bagit")]
    Bagit,
    #[serde(rename = "bagit_archive")]
    BagitArchive,
    #[serde(rename = "directory")]
    Directory,

}

impl ToString for ElementsFromType {
    fn to_string(&self) -> String {
        match self {
            Self::Archive => String::from("archive"),
            Self::Bagit => String::from("bagit"),
            Self::BagitArchive => String::from("bagit_archive"),
            Self::Directory => String::from("directory"),
        }
    }
}

impl Default for ElementsFromType {
    fn default() -> ElementsFromType {
        Self::Archive
    }
}




