/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ExportHistoryArchivePayload : Base model definition with common configuration used by all derived models.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ExportHistoryArchivePayload {
    /// A writable directory destination where the history will be exported using the `galaxy.files` URI infrastructure.
    #[serde(rename = "directory_uri", skip_serializing_if = "Option::is_none")]
    pub directory_uri: Option<String>,
    /// The name of the file containing the exported history.
    #[serde(rename = "file_name", skip_serializing_if = "Option::is_none")]
    pub file_name: Option<String>,
    /// Whether to force a rebuild of the history archive.
    #[serde(rename = "force", skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    /// Whether to export as gzip archive.
    #[serde(rename = "gzip", skip_serializing_if = "Option::is_none")]
    pub gzip: Option<bool>,
    /// Whether to include deleted datasets in the exported archive.
    #[serde(rename = "include_deleted", skip_serializing_if = "Option::is_none")]
    pub include_deleted: Option<bool>,
    /// Whether to include hidden datasets in the exported archive.
    #[serde(rename = "include_hidden", skip_serializing_if = "Option::is_none")]
    pub include_hidden: Option<bool>,
}

impl ExportHistoryArchivePayload {
    /// Base model definition with common configuration used by all derived models.
    pub fn new() -> ExportHistoryArchivePayload {
        ExportHistoryArchivePayload {
            directory_uri: None,
            file_name: None,
            force: None,
            gzip: None,
            include_deleted: None,
            include_hidden: None,
        }
    }
}


