/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Extra : Optional extra information about this shareable resource that may be of interest. The contents of this field depend on the particular resource.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Extra {
    /// Indicates whether the resource can be directly shared or requires further actions.
    #[serde(rename = "can_share", skip_serializing_if = "Option::is_none")]
    pub can_share: Option<bool>,
}

impl Extra {
    /// Optional extra information about this shareable resource that may be of interest. The contents of this field depend on the particular resource.
    pub fn new() -> Extra {
        Extra {
            can_share: None,
        }
    }
}


