/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FetchDataPayload {
    /// The encoded ID of the history associated with this item.
    #[serde(rename = "history_id")]
    pub history_id: String,
    #[serde(rename = "targets")]
    pub targets: Vec<crate::models::TargetsInner>,
}

impl FetchDataPayload {
    pub fn new(history_id: String, targets: Vec<crate::models::TargetsInner>) -> FetchDataPayload {
        FetchDataPayload {
            history_id,
            targets,
        }
    }
}


