/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FtpImportTarget {
    /// Decompress compressed data before sniffing?
    #[serde(rename = "auto_decompress", skip_serializing_if = "Option::is_none")]
    pub auto_decompress: Option<bool>,
    #[serde(rename = "collection_type", skip_serializing_if = "Option::is_none")]
    pub collection_type: Option<String>,
    #[serde(rename = "destination")]
    pub destination: Box<crate::models::HdcaDestination>,
    #[serde(rename = "elements_from", skip_serializing_if = "Option::is_none")]
    pub elements_from: Option<crate::models::ElementsFromType>,
    #[serde(rename = "ftp_path")]
    pub ftp_path: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "src")]
    pub src: Src,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl FtpImportTarget {
    pub fn new(destination: crate::models::HdcaDestination, ftp_path: String, src: Src) -> FtpImportTarget {
        FtpImportTarget {
            auto_decompress: None,
            collection_type: None,
            destination: Box::new(destination),
            elements_from: None,
            ftp_path,
            name: None,
            src,
            tags: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Src {
    #[serde(rename = "ftp_import")]
    FtpImport,
}

impl Default for Src {
    fn default() -> Src {
        Self::FtpImport
    }
}

