/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GalaxyModelJobStates : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GalaxyModelJobStates {
    #[serde(rename = "new")]
    New,
    #[serde(rename = "resubmitted")]
    Resubmitted,
    #[serde(rename = "upload")]
    Upload,
    #[serde(rename = "waiting")]
    Waiting,
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "deleting")]
    Deleting,
    #[serde(rename = "deleted")]
    Deleted,
    #[serde(rename = "deleted_new")]
    DeletedNew,
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "stopped")]
    Stopped,

}

impl ToString for GalaxyModelJobStates {
    fn to_string(&self) -> String {
        match self {
            Self::New => String::from("new"),
            Self::Resubmitted => String::from("resubmitted"),
            Self::Upload => String::from("upload"),
            Self::Waiting => String::from("waiting"),
            Self::Queued => String::from("queued"),
            Self::Running => String::from("running"),
            Self::Ok => String::from("ok"),
            Self::Error => String::from("error"),
            Self::Failed => String::from("failed"),
            Self::Paused => String::from("paused"),
            Self::Deleting => String::from("deleting"),
            Self::Deleted => String::from("deleted"),
            Self::DeletedNew => String::from("deleted_new"),
            Self::Stop => String::from("stop"),
            Self::Stopped => String::from("stopped"),
        }
    }
}

impl Default for GalaxyModelJobStates {
    fn default() -> GalaxyModelJobStates {
        Self::New
    }
}




