/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Group : Information about a user group associated with a quota.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Group {
    /// Encoded group ID
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the database model class.
    #[serde(rename = "model_class", skip_serializing_if = "Option::is_none")]
    pub model_class: Option<String>,
    /// The name of the group.
    #[serde(rename = "name")]
    pub name: String,
}

impl Group {
    /// Information about a user group associated with a quota.
    pub fn new(id: String, name: String) -> Group {
        Group {
            id,
            model_class: None,
            name,
        }
    }
}


