/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// HdaObject : History Dataset Association Object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HdaObject {
    /// Whether this dataset belongs to a history (HDA) or a library (LDDA).
    #[serde(rename = "hda_ldda", skip_serializing_if = "Option::is_none")]
    pub hda_ldda: Option<Box<crate::models::DatasetSourceType>>,
    /// The encoded ID of the history associated with this item.
    #[serde(rename = "history_id")]
    pub history_id: String,
    /// The encoded ID of this entity.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the database model class.
    #[serde(rename = "model_class", skip_serializing_if = "Option::is_none")]
    pub model_class: Option<String>,
    /// The current state of this dataset.
    #[serde(rename = "state")]
    pub state: Box<crate::models::GalaxyModelDatasetStates>,
}

impl HdaObject {
    /// History Dataset Association Object
    pub fn new(history_id: String, id: String, state: crate::models::GalaxyModelDatasetStates) -> HdaObject {
        HdaObject {
            hda_ldda: None,
            history_id,
            id,
            model_class: None,
            state: Box::new(state),
        }
    }
}


