/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// HistoryContentsApiHistoriesHistoryIdContentsGet200Response : List of history content items. Can contain different views and kinds of items.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HistoryContentsApiHistoriesHistoryIdContentsGet200Response {
}

impl HistoryContentsApiHistoriesHistoryIdContentsGet200Response {
    /// List of history content items. Can contain different views and kinds of items.
    pub fn new() -> HistoryContentsApiHistoriesHistoryIdContentsGet200Response {
        HistoryContentsApiHistoriesHistoryIdContentsGet200Response {
        }
    }
}


