/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// HistoryContentBulkOperationPayload : Base model definition with common configuration used by all derived models.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HistoryContentBulkOperationPayload {
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::HistoryContentItem>>,
    #[serde(rename = "operation")]
    pub operation: crate::models::HistoryContentItemOperation,
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<crate::models::Params>>,
}

impl HistoryContentBulkOperationPayload {
    /// Base model definition with common configuration used by all derived models.
    pub fn new(operation: crate::models::HistoryContentItemOperation) -> HistoryContentBulkOperationPayload {
        HistoryContentBulkOperationPayload {
            items: None,
            operation,
            params: None,
        }
    }
}


