/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// HistorySummary : History summary information.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HistorySummary {
    /// An annotation to provide details or to help understand the purpose and usage of this item.
    #[serde(rename = "annotation")]
    pub annotation: String,
    /// Whether this item is marked as deleted.
    #[serde(rename = "deleted")]
    pub deleted: bool,
    /// The encoded ID of this entity.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the database model class.
    #[serde(rename = "model_class", skip_serializing_if = "Option::is_none")]
    pub model_class: Option<String>,
    /// The name of the history.
    #[serde(rename = "name")]
    pub name: String,
    /// Whether this resource is currently publicly available to all users.
    #[serde(rename = "published")]
    pub published: bool,
    /// Whether this item has been permanently removed.
    #[serde(rename = "purged")]
    pub purged: bool,
    /// The collection of tags associated with an item.
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    /// The relative URL to access this item.
    #[serde(rename = "url")]
    pub url: String,
}

impl HistorySummary {
    /// History summary information.
    pub fn new(annotation: String, deleted: bool, id: String, name: String, published: bool, purged: bool, tags: Vec<String>, url: String) -> HistorySummary {
        HistorySummary {
            annotation,
            deleted,
            id,
            model_class: None,
            name,
            published,
            purged,
            tags,
            url,
        }
    }
}


