/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Hyperlink : Represents some text with an Hyperlink.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Hyperlink {
    /// Specifies the linked document, resource, or location.
    #[serde(rename = "href")]
    pub href: String,
    /// Specifies where to open the linked document.
    #[serde(rename = "target")]
    pub target: String,
    /// The text placeholder for the link.
    #[serde(rename = "text")]
    pub text: String,
}

impl Hyperlink {
    /// Represents some text with an Hyperlink.
    pub fn new(href: String, target: String, text: String) -> Hyperlink {
        Hyperlink {
            href,
            target,
            text,
        }
    }
}


