/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JobStateSummary : Overview of the job states working inside the dataset collection.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JobStateSummary {
    /// Total number of jobs associated with a dataset collection.
    #[serde(rename = "all_jobs", skip_serializing_if = "Option::is_none")]
    pub all_jobs: Option<i32>,
    /// Number of jobs in the `deleted` state.
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<i32>,
    /// Number of jobs in the `deleted_new` state.
    #[serde(rename = "deleted_new", skip_serializing_if = "Option::is_none")]
    pub deleted_new: Option<i32>,
    /// Number of jobs in the `error` state.
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<i32>,
    /// Number of jobs in the `failed` state.
    #[serde(rename = "failed", skip_serializing_if = "Option::is_none")]
    pub failed: Option<i32>,
    /// Number of jobs in the `new` state.
    #[serde(rename = "new", skip_serializing_if = "Option::is_none")]
    pub new: Option<i32>,
    /// Number of jobs in the `ok` state.
    #[serde(rename = "ok", skip_serializing_if = "Option::is_none")]
    pub ok: Option<i32>,
    /// Number of jobs in the `paused` state.
    #[serde(rename = "paused", skip_serializing_if = "Option::is_none")]
    pub paused: Option<i32>,
    /// Number of jobs in the `queued` state.
    #[serde(rename = "queued", skip_serializing_if = "Option::is_none")]
    pub queued: Option<i32>,
    /// Number of jobs in the `resubmitted` state.
    #[serde(rename = "resubmitted", skip_serializing_if = "Option::is_none")]
    pub resubmitted: Option<i32>,
    /// Number of jobs in the `running` state.
    #[serde(rename = "running", skip_serializing_if = "Option::is_none")]
    pub running: Option<i32>,
    /// Number of jobs in the `upload` state.
    #[serde(rename = "upload", skip_serializing_if = "Option::is_none")]
    pub upload: Option<i32>,
    /// Number of jobs in the `waiting` state.
    #[serde(rename = "waiting", skip_serializing_if = "Option::is_none")]
    pub waiting: Option<i32>,
}

impl JobStateSummary {
    /// Overview of the job states working inside the dataset collection.
    pub fn new() -> JobStateSummary {
        JobStateSummary {
            all_jobs: None,
            deleted: None,
            deleted_new: None,
            error: None,
            failed: None,
            new: None,
            ok: None,
            paused: None,
            queued: None,
            resubmitted: None,
            running: None,
            upload: None,
            waiting: None,
        }
    }
}


