/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JobExportHistoryArchiveModel : Base model definition with common configuration used by all derived models.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JobExportHistoryArchiveModel {
    /// Relative API URL to download the exported history archive.
    #[serde(rename = "download_url")]
    pub download_url: String,
    /// Fully qualified URL to download the latests version of the exported history archive.
    #[serde(rename = "external_download_latest_url")]
    pub external_download_latest_url: String,
    /// Fully qualified URL to download this particular version of the exported history archive.
    #[serde(rename = "external_download_permanent_url")]
    pub external_download_permanent_url: String,
    /// The encoded database ID of the job that is currently processing a particular request.
    #[serde(rename = "id")]
    pub id: String,
    /// The encoded database ID of the job that generated this history export archive.
    #[serde(rename = "job_id")]
    pub job_id: String,
    /// Whether the history archive is currently being built or in preparation.
    #[serde(rename = "preparing")]
    pub preparing: bool,
    /// Whether the export history job has completed successfully and the archive is ready to download
    #[serde(rename = "ready")]
    pub ready: bool,
    /// False, if a new export archive should be generated for the corresponding history.
    #[serde(rename = "up_to_date")]
    pub up_to_date: bool,
}

impl JobExportHistoryArchiveModel {
    /// Base model definition with common configuration used by all derived models.
    pub fn new(download_url: String, external_download_latest_url: String, external_download_permanent_url: String, id: String, job_id: String, preparing: bool, ready: bool, up_to_date: bool) -> JobExportHistoryArchiveModel {
        JobExportHistoryArchiveModel {
            download_url,
            external_download_latest_url,
            external_download_permanent_url,
            id,
            job_id,
            preparing,
            ready,
            up_to_date,
        }
    }
}


