/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LibraryFolderCurrentPermissions {
    /// A list containing pairs of role names and corresponding encoded IDs which can add items to the Library folder.
    #[serde(rename = "add_library_item_role_list")]
    pub add_library_item_role_list: Vec<Vec<String>>,
    /// A list containing pairs of role names and corresponding encoded IDs which can manage the Library folder.
    #[serde(rename = "manage_folder_role_list")]
    pub manage_folder_role_list: Vec<Vec<String>>,
    /// A list containing pairs of role names and corresponding encoded IDs which can modify the Library folder.
    #[serde(rename = "modify_folder_role_list")]
    pub modify_folder_role_list: Vec<Vec<String>>,
}

impl LibraryFolderCurrentPermissions {
    pub fn new(add_library_item_role_list: Vec<Vec<String>>, manage_folder_role_list: Vec<Vec<String>>, modify_folder_role_list: Vec<Vec<String>>) -> LibraryFolderCurrentPermissions {
        LibraryFolderCurrentPermissions {
            add_library_item_role_list,
            manage_folder_role_list,
            modify_folder_role_list,
        }
    }
}


