/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LibraryPermissionScope : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LibraryPermissionScope {
    #[serde(rename = "current")]
    Current,
    #[serde(rename = "available")]
    Available,

}

impl ToString for LibraryPermissionScope {
    fn to_string(&self) -> String {
        match self {
            Self::Current => String::from("current"),
            Self::Available => String::from("available"),
        }
    }
}

impl Default for LibraryPermissionScope {
    fn default() -> LibraryPermissionScope {
        Self::Current
    }
}




