/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LibraryFolderPermissionsPayload : Base model definition with common configuration used by all derived models.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LibraryFolderPermissionsPayload {
    /// Indicates what action should be performed on the library folder.
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<Box<crate::models::LibraryFolderPermissionAction>>,
    #[serde(rename = "add_ids[]", skip_serializing_if = "Option::is_none")]
    pub add_ids_left_square_bracket_right_square_bracket: Option<Box<crate::models::AddIds>>,
    #[serde(rename = "manage_ids[]", skip_serializing_if = "Option::is_none")]
    pub manage_ids_left_square_bracket_right_square_bracket: Option<Box<crate::models::ManageIds>>,
    #[serde(rename = "modify_ids[]", skip_serializing_if = "Option::is_none")]
    pub modify_ids_left_square_bracket_right_square_bracket: Option<Box<crate::models::ModifyIds>>,
}

impl LibraryFolderPermissionsPayload {
    /// Base model definition with common configuration used by all derived models.
    pub fn new() -> LibraryFolderPermissionsPayload {
        LibraryFolderPermissionsPayload {
            action: None,
            add_ids_left_square_bracket_right_square_bracket: None,
            manage_ids_left_square_bracket_right_square_bracket: None,
            modify_ids_left_square_bracket_right_square_bracket: None,
        }
    }
}


