/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LibraryPermissionsPayload : Base model definition with common configuration used by all derived models.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LibraryPermissionsPayload {
    #[serde(rename = "access_ids[]", skip_serializing_if = "Option::is_none")]
    pub access_ids_left_square_bracket_right_square_bracket: Option<Box<crate::models::AccessIds>>,
    /// Indicates what action should be performed on the Library.
    #[serde(rename = "action")]
    pub action: Box<crate::models::LibraryPermissionAction>,
    #[serde(rename = "add_ids[]", skip_serializing_if = "Option::is_none")]
    pub add_ids_left_square_bracket_right_square_bracket: Option<Box<crate::models::AddIds>>,
    #[serde(rename = "manage_ids[]", skip_serializing_if = "Option::is_none")]
    pub manage_ids_left_square_bracket_right_square_bracket: Option<Box<crate::models::ManageIds>>,
    #[serde(rename = "modify_ids[]", skip_serializing_if = "Option::is_none")]
    pub modify_ids_left_square_bracket_right_square_bracket: Option<Box<crate::models::ModifyIds>>,
}

impl LibraryPermissionsPayload {
    /// Base model definition with common configuration used by all derived models.
    pub fn new(action: crate::models::LibraryPermissionAction) -> LibraryPermissionsPayload {
        LibraryPermissionsPayload {
            access_ids_left_square_bracket_right_square_bracket: None,
            action: Box::new(action),
            add_ids_left_square_bracket_right_square_bracket: None,
            manage_ids_left_square_bracket_right_square_bracket: None,
            modify_ids_left_square_bracket_right_square_bracket: None,
        }
    }
}


