/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LibraryCurrentPermissions {
    /// A list containing pairs of role names and corresponding encoded IDs which have access to the Library.
    #[serde(rename = "access_library_role_list")]
    pub access_library_role_list: Vec<Vec<String>>,
    /// A list containing pairs of role names and corresponding encoded IDs which can add items to the Library.
    #[serde(rename = "add_library_item_role_list")]
    pub add_library_item_role_list: Vec<Vec<String>>,
    /// A list containing pairs of role names and corresponding encoded IDs which can manage the Library.
    #[serde(rename = "manage_library_role_list")]
    pub manage_library_role_list: Vec<Vec<String>>,
    /// A list containing pairs of role names and corresponding encoded IDs which can modify the Library.
    #[serde(rename = "modify_library_role_list")]
    pub modify_library_role_list: Vec<Vec<String>>,
}

impl LibraryCurrentPermissions {
    pub fn new(access_library_role_list: Vec<Vec<String>>, add_library_item_role_list: Vec<Vec<String>>, manage_library_role_list: Vec<Vec<String>>, modify_library_role_list: Vec<Vec<String>>) -> LibraryCurrentPermissions {
        LibraryCurrentPermissions {
            access_library_role_list,
            add_library_item_role_list,
            manage_library_role_list,
            modify_library_role_list,
        }
    }
}


