/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LibrarySummary {
    /// Whether the current user can add contents to this Library.
    #[serde(rename = "can_user_add")]
    pub can_user_add: bool,
    /// Whether the current user can manage the Library and its contents.
    #[serde(rename = "can_user_manage")]
    pub can_user_manage: bool,
    /// Whether the current user can modify this Library.
    #[serde(rename = "can_user_modify")]
    pub can_user_modify: bool,
    /// The time and date this item was created.
    #[serde(rename = "create_time")]
    pub create_time: String,
    /// Nice time representation of the creation date.
    #[serde(rename = "create_time_pretty")]
    pub create_time_pretty: String,
    /// Whether this Library has been deleted.
    #[serde(rename = "deleted")]
    pub deleted: bool,
    /// A detailed description of the Library.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Encoded ID of the Library.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the database model class.
    #[serde(rename = "model_class", skip_serializing_if = "Option::is_none")]
    pub model_class: Option<String>,
    /// The name of the Library.
    #[serde(rename = "name")]
    pub name: String,
    /// Whether this Library has been deleted.
    #[serde(rename = "public")]
    pub public: bool,
    /// Encoded ID of the Library's base folder.
    #[serde(rename = "root_folder_id")]
    pub root_folder_id: String,
    /// A short text describing the contents of the Library.
    #[serde(rename = "synopsis", skip_serializing_if = "Option::is_none")]
    pub synopsis: Option<String>,
}

impl LibrarySummary {
    pub fn new(can_user_add: bool, can_user_manage: bool, can_user_modify: bool, create_time: String, create_time_pretty: String, deleted: bool, id: String, name: String, public: bool, root_folder_id: String) -> LibrarySummary {
        LibrarySummary {
            can_user_add,
            can_user_manage,
            can_user_modify,
            create_time,
            create_time_pretty,
            deleted,
            description: None,
            id,
            model_class: None,
            name,
            public,
            root_folder_id,
            synopsis: None,
        }
    }
}


