/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ModelStoreFormat : Available types of model stores for export.

/// Available types of model stores for export.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ModelStoreFormat {
    #[serde(rename = "tgz")]
    Tgz,
    #[serde(rename = "tar")]
    Tar,
    #[serde(rename = "tar.gz")]
    TarPeriodGz,
    #[serde(rename = "bag.zip")]
    BagPeriodZip,
    #[serde(rename = "bag.tar")]
    BagPeriodTar,
    #[serde(rename = "bag.tgz")]
    BagPeriodTgz,

}

impl ToString for ModelStoreFormat {
    fn to_string(&self) -> String {
        match self {
            Self::Tgz => String::from("tgz"),
            Self::Tar => String::from("tar"),
            Self::TarPeriodGz => String::from("tar.gz"),
            Self::BagPeriodZip => String::from("bag.zip"),
            Self::BagPeriodTar => String::from("bag.tar"),
            Self::BagPeriodTgz => String::from("bag.tgz"),
        }
    }
}

impl Default for ModelStoreFormat {
    fn default() -> ModelStoreFormat {
        Self::Tgz
    }
}




