/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ModifyIds : A list of role encoded IDs defining roles that should have modify permission on the library.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ModifyIds {
}

impl ModifyIds {
    /// A list of role encoded IDs defining roles that should have modify permission on the library.
    pub fn new() -> ModifyIds {
        ModifyIds {
        }
    }
}


