/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PreClick : Elements that receive a click() event before the step is shown



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PreClick {
}

impl PreClick {
    /// Elements that receive a click() event before the step is shown
    pub fn new() -> PreClick {
        PreClick {
        }
    }
}


