/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// QuotaSummary : Contains basic information about a Quota



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QuotaSummary {
    /// The `encoded identifier` of the quota.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the database model class.
    #[serde(rename = "model_class", skip_serializing_if = "Option::is_none")]
    pub model_class: Option<String>,
    /// The name of the quota. This must be unique within a Galaxy instance.
    #[serde(rename = "name")]
    pub name: String,
    /// The relative URL to get this particular Quota details from the rest API.
    #[serde(rename = "url")]
    pub url: String,
}

impl QuotaSummary {
    /// Contains basic information about a Quota
    pub fn new(id: String, name: String, url: String) -> QuotaSummary {
        QuotaSummary {
            id,
            model_class: None,
            name,
            url,
        }
    }
}


