/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// QuotaOperation : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QuotaOperation {
    #[serde(rename = "=")]
    Equal,
    #[serde(rename = "+")]
    Plus,
    #[serde(rename = "-")]
    ,

}

impl ToString for QuotaOperation {
    fn to_string(&self) -> String {
        match self {
            Self::Equal => String::from("="),
            Self::Plus => String::from("+"),
            Self:: => String::from("-"),
        }
    }
}

impl Default for QuotaOperation {
    fn default() -> QuotaOperation {
        Self::Equal
    }
}




