/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RemoteFilesFormat : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RemoteFilesFormat {
    #[serde(rename = "flat")]
    Flat,
    #[serde(rename = "jstree")]
    Jstree,
    #[serde(rename = "uri")]
    Uri,

}

impl ToString for RemoteFilesFormat {
    fn to_string(&self) -> String {
        match self {
            Self::Flat => String::from("flat"),
            Self::Jstree => String::from("jstree"),
            Self::Uri => String::from("uri"),
        }
    }
}

impl Default for RemoteFilesFormat {
    fn default() -> RemoteFilesFormat {
        Self::Flat
    }
}




