/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RemoteFilesDisableMode : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RemoteFilesDisableMode {
    #[serde(rename = "folders")]
    Folders,
    #[serde(rename = "files")]
    Files,

}

impl ToString for RemoteFilesDisableMode {
    fn to_string(&self) -> String {
        match self {
            Self::Folders => String::from("folders"),
            Self::Files => String::from("files"),
        }
    }
}

impl Default for RemoteFilesDisableMode {
    fn default() -> RemoteFilesDisableMode {
        Self::Folders
    }
}




