/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResponseIndexApiHistoriesHistoryIdContentsTypeSGet {
    /// The items matching the search query. Only the items fitting in the current page limit will be returned.
    #[serde(rename = "contents")]
    pub contents: Vec<crate::models::ResponseIndexApiDatasetsGetInner>,
    #[serde(rename = "stats")]
    pub stats: Box<crate::models::Stats>,
}

impl ResponseIndexApiHistoriesHistoryIdContentsTypeSGet {
    pub fn new(contents: Vec<crate::models::ResponseIndexApiDatasetsGetInner>, stats: crate::models::Stats) -> ResponseIndexApiHistoriesHistoryIdContentsTypeSGet {
        ResponseIndexApiHistoriesHistoryIdContentsTypeSGet {
            contents,
            stats: Box::new(stats),
        }
    }
}


