/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResponseIndexApiDatatypesGet {
}

impl ResponseIndexApiDatatypesGet {
    pub fn new() -> ResponseIndexApiDatatypesGet {
        ResponseIndexApiDatatypesGet {
        }
    }
}


