/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ShareWithExtra {
    /// Indicates whether the resource can be directly shared or requires further actions.
    #[serde(rename = "can_share", skip_serializing_if = "Option::is_none")]
    pub can_share: Option<bool>,
}

impl ShareWithExtra {
    pub fn new() -> ShareWithExtra {
        ShareWithExtra {
            can_share: None,
        }
    }
}


