/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TagOperationParams : Base model definition with common configuration used by all derived models.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TagOperationParams {
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    #[serde(rename = "type")]
    pub r#type: Box<crate::models::Type>,
}

impl TagOperationParams {
    /// Base model definition with common configuration used by all derived models.
    pub fn new(tags: Vec<String>, r#type: crate::models::Type) -> TagOperationParams {
        TagOperationParams {
            tags,
            r#type: Box::new(r#type),
        }
    }
}


