/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TaggableItemClass : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TaggableItemClass {
    #[serde(rename = "History")]
    History,
    #[serde(rename = "HistoryDatasetAssociation")]
    HistoryDatasetAssociation,
    #[serde(rename = "LibraryDatasetDatasetAssociation")]
    LibraryDatasetDatasetAssociation,
    #[serde(rename = "Page")]
    Page,
    #[serde(rename = "WorkflowStep")]
    WorkflowStep,
    #[serde(rename = "StoredWorkflow")]
    StoredWorkflow,
    #[serde(rename = "Visualization")]
    Visualization,
    #[serde(rename = "HistoryDatasetCollection")]
    HistoryDatasetCollection,
    #[serde(rename = "LibraryDatasetCollection")]
    LibraryDatasetCollection,
    #[serde(rename = "Tool")]
    Tool,

}

impl ToString for TaggableItemClass {
    fn to_string(&self) -> String {
        match self {
            Self::History => String::from("History"),
            Self::HistoryDatasetAssociation => String::from("HistoryDatasetAssociation"),
            Self::LibraryDatasetDatasetAssociation => String::from("LibraryDatasetDatasetAssociation"),
            Self::Page => String::from("Page"),
            Self::WorkflowStep => String::from("WorkflowStep"),
            Self::StoredWorkflow => String::from("StoredWorkflow"),
            Self::Visualization => String::from("Visualization"),
            Self::HistoryDatasetCollection => String::from("HistoryDatasetCollection"),
            Self::LibraryDatasetCollection => String::from("LibraryDatasetCollection"),
            Self::Tool => String::from("Tool"),
        }
    }
}

impl Default for TaggableItemClass {
    fn default() -> TaggableItemClass {
        Self::History
    }
}




