/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ToolDataDetails {
    /// A list of column names
    #[serde(rename = "columns")]
    pub columns: Vec<String>,
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Vec<Vec<String>>>,
    /// The name of class modelling this tool data
    #[serde(rename = "model_class")]
    pub model_class: String,
    /// The name of this tool data entry
    #[serde(rename = "name")]
    pub name: String,
}

impl ToolDataDetails {
    pub fn new(columns: Vec<String>, model_class: String, name: String) -> ToolDataDetails {
        ToolDataDetails {
            columns,
            fields: None,
            model_class,
            name,
        }
    }
}


