/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ToolDataField {
    /// A list of directories where the data files are stored
    #[serde(rename = "base_dir")]
    pub base_dir: Vec<String>,
    #[serde(rename = "fields")]
    pub fields: ::std::collections::HashMap<String, String>,
    /// A dictionary of file names and their size in bytes
    #[serde(rename = "files")]
    pub files: ::std::collections::HashMap<String, i32>,
    /// SHA1 Hash
    #[serde(rename = "fingerprint")]
    pub fingerprint: String,
    /// The name of class modelling this tool data field
    #[serde(rename = "model_class")]
    pub model_class: String,
    /// The name of the field
    #[serde(rename = "name")]
    pub name: String,
}

impl ToolDataField {
    pub fn new(base_dir: Vec<String>, fields: ::std::collections::HashMap<String, String>, files: ::std::collections::HashMap<String, i32>, fingerprint: String, model_class: String, name: String) -> ToolDataField {
        ToolDataField {
            base_dir,
            fields,
            files,
            fingerprint,
            model_class,
            name,
        }
    }
}


