/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Tour {
    /// Tour description
    #[serde(rename = "description")]
    pub description: String,
    /// Tour identifier
    #[serde(rename = "id")]
    pub id: String,
    /// Name of tour
    #[serde(rename = "name")]
    pub name: String,
    /// Requirements to run the tour.
    #[serde(rename = "requirements")]
    pub requirements: Vec<crate::models::Requirement>,
    /// Topic topic tags
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
}

impl Tour {
    pub fn new(description: String, id: String, name: String, requirements: Vec<crate::models::Requirement>, tags: Vec<String>) -> Tour {
        Tour {
            description,
            id,
            name,
            requirements,
            tags,
        }
    }
}


