/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TourStep {
    /// Text shown to the user
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// CSS selector for the element to be described/clicked
    #[serde(rename = "element", skip_serializing_if = "Option::is_none")]
    pub element: Option<String>,
    /// Placement of the text box relative to the selected element
    #[serde(rename = "placement", skip_serializing_if = "Option::is_none")]
    pub placement: Option<String>,
    #[serde(rename = "postclick", skip_serializing_if = "Option::is_none")]
    pub postclick: Option<Box<crate::models::PostClick>>,
    #[serde(rename = "preclick", skip_serializing_if = "Option::is_none")]
    pub preclick: Option<Box<crate::models::PreClick>>,
    /// Text to insert if element is a text box (e.g. tool search or upload)
    #[serde(rename = "textinsert", skip_serializing_if = "Option::is_none")]
    pub textinsert: Option<String>,
    /// Title displayed in the header of the step container
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl TourStep {
    pub fn new() -> TourStep {
        TourStep {
            content: None,
            element: None,
            placement: None,
            postclick: None,
            preclick: None,
            textinsert: None,
            title: None,
        }
    }
}


