/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserEmail {
    /// The email of the user.
    #[serde(rename = "email")]
    pub email: String,
    /// The encoded ID of the user.
    #[serde(rename = "id")]
    pub id: String,
}

impl UserEmail {
    pub fn new(email: String, id: String) -> UserEmail {
        UserEmail {
            email,
            id,
        }
    }
}


