/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UserModel : User in a transaction context.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserModel {
    /// User is active
    #[serde(rename = "active")]
    pub active: bool,
    /// User is deleted
    #[serde(rename = "deleted")]
    pub deleted: bool,
    /// User email
    #[serde(rename = "email")]
    pub email: String,
    /// User ID
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "last_password_change", skip_serializing_if = "Option::is_none")]
    pub last_password_change: Option<String>,
    /// The name of the database model class.
    #[serde(rename = "model_class", skip_serializing_if = "Option::is_none")]
    pub model_class: Option<String>,
    /// User username
    #[serde(rename = "username")]
    pub username: String,
}

impl UserModel {
    /// User in a transaction context.
    pub fn new(active: bool, deleted: bool, email: String, id: String, username: String) -> UserModel {
        UserModel {
            active,
            deleted,
            email,
            id,
            last_password_change: None,
            model_class: None,
            username,
        }
    }
}


