/*
 * Galaxy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 22.05.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ValidatedStates : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ValidatedStates {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "invalid")]
    Invalid,
    #[serde(rename = "ok")]
    Ok,

}

impl ToString for ValidatedStates {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::Invalid => String::from("invalid"),
            Self::Ok => String::from("ok"),
        }
    }
}

impl Default for ValidatedStates {
    fn default() -> ValidatedStates {
        Self::Unknown
    }
}




